version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  go-example:
    lang: golang-middleware
    handler: ./go-example
    image: alexellis2/go-example:latest

configuration:
  templates:
    - name: golang-middleware

